[package]
name = "macros"
version = "0.1.0"
authors = ["Ethan <liu.zy.ethan@gmail.com>"]
edition = "2021"
license = "MIT or Apache-2.0"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.95"
futures = "0.3.28"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
